services:
  - type: web
    runtime: python
    name: my-app-backend
    buildCommand: pip install -r requirements.txt
    startCommand: python src/backend/server.py
    envVars:
      - key: PORT
        value: 5173
    

  - type: web
    runtime: static
    name: my-app-frontend
    buildCommand: npm install && npm run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    
